dataset:
  auto_augment: rand-m9-mstd0.5-inc1
  interpolation: bicubic
  name: cotton80
  num_workers: 8
  re_count: 1
  re_mode: pixel
  re_prob: 0.25
  root: ./data
logging:
  log_interval: 100
  use_tensorboard: false
  use_wandb: false
loss:
  a: 1.0
  b: 1.0
  ema_decay: 0.1
  label_smoothing: 0.5
  tau_max: 1.6
  tau_min: 0.8
  type: vace # vace or ce
model:
  backbone: resnet50.fb_swsl_ig1b_ft_in1k
  pretrained: true
optimizer:
  betas:
    - 0.9
    - 0.999
  lr: 1.0e-4
  momentum: 0.9
  nesterov: true
  type: adamw
  weight_decay: 0.0001
output:
  checkpoint_dir: ./outputs/checkpoints
  log_dir: ./outputs/logs
  save_frequency: 10
project_name: vace
scheduler:
  eta_min: 0.0
  gamma: 0.1
  milestones: null
  step_size: 30
  type: cosine
seed: 42
training:
  batch_size: 64
  epochs: 100
  use_amp: true
