dataset:
  auto_augment: rand-m9-mstd0.5-inc1
  interpolation: bicubic
  name: cotton80
  num_workers: 4
  re_count: 1
  re_mode: pixel
  re_prob: 0.25
  root: ./data
logging:
  log_interval: 100
  use_tensorboard: false
  use_wandb: false
loss:
  a: 1.0
  b: 1.0
  ema_decay: 0.1
  label_smoothing: 0.0
  tau_max: 2.0
  tau_min: 0.5
  type: vace
model:
  backbone: efficientnet_b0.ra_in1k
  pretrained: true
optimizer:
  betas:
    - 0.9
    - 0.999
  lr: 0.05
  momentum: 0.9
  nesterov: true
  type: sgd
  weight_decay: 0.0001
output:
  checkpoint_dir: ./outputs/checkpoints
  log_dir: ./outputs/logs
  save_frequency: 10
project_name: vace
scheduler:
  eta_min: 0.0
  gamma: 0.1
  milestones: null
  step_size: 30
  type: cosine
seed: 42
training:
  batch_size: 128
  epochs: 50
  use_amp: true
